const ACHIEVEMENT_ICONS: Record<string, string> = {
  first_dip: '👣',
  regular: '🔄',
  winter_starter: '🌨️',
  ice_king: '🥶',
  arctic_hero: '❄️',
  sub_zero: '🧊',
  ice_block: '🪨',
  minute_man: '⏱️',
  three_minute: '⏳',
  endurance: '🏊',
  marathon: '🏁',
  week_warrior: '🎯',
  month_streak: '📅',
  comeback: '🔁',
  weekly_habit: '📆',
  mood_boost: '📈',
  zen: '🧘',
  swear_storm: '😤',
  silent_seal: '🦭',
  hot_cold: '♨️',
  sauna_regular: '🧖',
  sauna_majuri: '👑',
  long_sauna: '🔥',
  explorer: '🗺️',
  home_ground: '🏠',
  year_round: '🌍',
  new_year: '🎆',
  selfie_star: '📸',
  early_bird: '🌅',
  winter_total: '⛄',
  cold_heart: '💙',
};

export const getAchievementIcon = (id: string): string => ACHIEVEMENT_ICONS[id] ?? '🏅';
